### ISSUE TITLE
6.0.2 final release checklist for Python 3.13 support

### ISSUE THREAD

**Issue by nitzmahone** [yaml/pyyaml#818]
Now that Python 3.13.0rc1 has been tagged, it's time to do a final release of 6.0.2 with 3.13 support.

* [x] Fix or kill `setup.py test` (#486 
* [x] Update python_requires metadata to [exclude < 3.8 ](https://github.com/yaml/pyyaml/pull/811#issuecomment-2164002142)
* [x] Update CI to test against 3.13.0rc1 (once manylinux and cibuildwheel are updated with 3.13.0rc1 support, or use private copies)
* [x] Do 6.0.2 final build and release
* [x] Yank 6.0.2rc1 from PyPI so < 3.8 users installing with `--pre` don't pick up something that won't build (but it's still available for anyone explicitly installing `pyyaml==6.0.2rc1`
